# Generated by Django 4.1.7 on 2023-03-31 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='descrição',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='livros_emprestimo', to='emprestimos.livro', verbose_name='livro'),
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.CharField(max_length=100, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=100, null=True, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
