# Generated by Django 4.1.7 on 2023-03-31 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_remove_livro_descrição_emprestimo_livro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='emprestimos.autor', verbose_name='Autor'),
        ),
    ]
