# Generated by Django 4.1.7 on 2023-03-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='emprestimos.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='emprestimos.autor', verbose_name='Autor'),
        ),
    ]
