# Generated by Django 4.1.7 on 2023-04-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_emprestimo_autor_alter_livro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
