# Generated by Django 4.1.7 on 2023-04-02 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_rename_usuario_perfil_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
    ]
